Compartment model develop
AIforGoodSimulator/model-server pull request #137
Opened 2020-11-12 21:08 UTC by icemachined

stochastic compartment model

2020-11-13 08:49 UTC, pardf requested changes
In fs/params/compartmental-model-stochastic_profile_params.csv, could we have parameter profiles similar to the CM please? Thanks.

2020-11-15 12:49 UTC, icemachined commented
> In fs/params/compartmental-model-stochastic_profile_params.csv, could we have parameter profiles similar to the CM please? Thanks.

Fixed

2020-11-15 14:24 UTC, pardf commented
@icemachined could you take a look at the code check please?

2020-11-16 00:42 UTC, pardf approved these changes

2020-11-16 00:42 UTC, merged