Flask appbuilder test - added access control
AIforGoodSimulator/model-server pull request #167
Opened 2020-11-27 05:33 UTC by pardf

Added user access control functionality
- using flask and its extensions particularly flask-login and flask-sqlalchemy
- modifications in the dash app
- updated web tests (x2)
- improved config.py for app setup and secrets management

2020-11-28 04:38 UTC, pardf commented
Hi @kariso2000, currently, SECRET_KEY in config.py needs to be disabled to pass all checks.

2020-11-29 22:44 UTC, kariso2000 requested changes
Please remove ai4good/webapp/db.sqlite.  This was created by me when I was testing some other code.

2020-11-30 00:51 UTC, pardf commented
> 
> 
> Please remove ai4good/webapp/db.sqlite. This was created by me when I was testing some other code.

Hi @kariso2000 db.sqlite removed as requested

2020-11-30 09:59 UTC, kariso2000 approved these changes

2020-12-02 11:00 UTC, billlyzhaoyh approved these changes

2021-01-13 16:03 UTC, merged